resources:
  - backend/deployment.yml
  - backend/service.yml
  - frontend/deployment.yml
  - frontend/service.yml

images:
  - name: 758862194321.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop-jan/production/backend
    newName: 758862194321.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop-jan/production/backend
    newTag: v1.0
    
  - name: 758862194321.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop-jan/production/frontend
    newName: 758862194321.dkr.ecr.us-east-1.amazonaws.com/dvn-workshop-jan/production/frontend
    newTag: v1.0